### ISSUE TITLE
Feature: Search for all APIs that use a specific API

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/hub#1]
For example, search for all APIs that use Ethereum (`w3://ens/ethereum.web3api.eth`).

Currently, Web3API schemas only contain references to their immediate dependencies. So for example, if `1inch` uses `uniswap`, and `uniswap` uses `ethereum`, using the immediate dependencies you'd only get `uniswap` as a search result.

In order to solve this, we'd have to perform multi-step querying where we first:
- get all packages that include ethereum
- for each package returned, get all packages that include that
- repeat recursively to show all options

This could be done on a backend service, or done in-app using multiple caching server (subgraph) queries.

**Comment by jeffscottward** [comment]
I would defer to whichever provides a faster user experience. I don't think this is the kind of tool where some centralized pieces make it a contentious issue.

**Comment by dOrgJelli** [comment]
Agreed, especially for features that related to aggregation and indexing for increased searchability. We could setup a serverless function that reads from & appends to a cache for this sort of dependency walking.

**Comment by dOrgJelli** [comment]
This requires the tracking of dependencies, which is not currently done. Going to close this for now.
