### ISSUE TITLE
DID changes when wallet changed and page reloaded

### ISSUE THREAD

**Issue by yariyzt** [polywrap/hub#143]
Steps
1. Login with first metamask wallet (we are logged in)
2. Logout and check DID
3. Change wallet (we see icon, that we logged in)
4. Refresh the page
5. Login with second metamask wallet (we are logged in)
6. Logout and check DID
https://www.loom.com/share/50c1d655086a4f5698307f109448b295

**Comment by Brioline** [comment]
Expected behavior if another did attached to second address
