### ISSUE TITLE
Issue when create with Provide ENS address

### ISSUE THREAD

**Issue by yariyzt** [polywrap/hub#148]
Steps

Previously create wrapper with ENS, then in next steps put it into ENS address field
1. Open home page
2. Click on Publish wrapper
3. Click on Provide ENS address 
4. Write ENS and click Next

http://joxi.ru/KAgQgVyHNLGvVm

**Comment by ramilexe** [comment]
Blocked by ENS Wrapper issue. Conversation in Discrord: https://discord.com/channels/796821176743362611/800802113038712853/960458910924431380
