### ISSUE TITLE
Add skeleton after page reload

### ISSUE THREAD

**Issue by vrijzinnig** [polywrap/hub#165]
**Steps:**

login 
reload the page

**AR:** not logged in state is shown for few seconds 

**ER:** add skeleton

**Comment by vrijzinnig** [comment]
No skeleton is shown https://i.imgur.com/Gvxr6oD.gif
No api was found is shown instead https://prnt.sc/Zryt8cfcbcTa

**Comment by ramilexe** [comment]
Instead of skeleton use the loader the same as in Playground

**Comment by Brioline** [comment]
Closed by https://github.com/polywrap/hub/pull/207/commits/6e0d74809847ad2c3011f23dde8bede7e7ebe61d
