### ISSUE TITLE
Switching network issue

### ISSUE THREAD

**Issue by vrijzinnig** [polywrap/hub#166]
**Steps:**
1. Choose Rinkeby or Ropsten in Metamask
2. Click on Login
3. Click on Connect and Choose Metamask

**AR:** Change network modal window is opened https://prnt.sc/26xbatq

**ER:** User connected with supported networks should not be asked to change the network

**Comment by Brioline** [comment]
Issue hasn't been resolved, as bnc-onboard connects to wallet on page loadup. Only 1 network can be provided to onboard process.
After logout -> changing network -> login, wallet prompts to connect to previously provided network, as WS connection was established on app loadup. Currently bnc onboard have no way to close this WS connection without page reload
