### ISSUE TITLE
Issues on Playground page

### ISSUE THREAD

**Issue by vrijzinnig** [polywrap/hub#168]
1. Make scroll bar longer https://prnt.sc/26x2gv3
2. Cursor is jumping down when user fills out the variables https://prnt.sc/26xcow4
3. UI issue with scrollbar on Variables https://prnt.sc/26xcnzq
4. Cursor is missing on Search wrappers https://prnt.sc/26xcpja
5. Search API's field duplicates what was entered on Search wrappers field but it is invisible until user emphasizes it https://prnt.sc/26xcs6e and when no results found it shows red cursive line https://prnt.sc/26xcr31
6. Add 'No results found' on search field https://prnt.sc/26xcuox

**Comment by vrijzinnig** [comment]
@Brioline Issue with scroll bar on Variables is still repro
https://prnt.sc/1r2ZtIEjYDAf
Some new issues discovered:
1. Red rectangle appears, when enter a wrong text but it does not fit the lines
https://prnt.sc/_HswUJRn_SQ-
2. UI on Variables is broken when Schema is shown
https://prnt.sc/tVmBScuQUQOF
3. Scroll bar on Schema is different from a scroll bar on query and vars fields
https://prnt.sc/5xdBqwB_K_V2

**Comment by Brioline** [comment]
@vrijzinnig 
White bars on variable scrollbar indicates current scope ( "{ }" ) 
1. Red bar is proportionally relative to errors in textfield. If you select a line with an error, you'll see '-' indicator on scrollbar will go to start or end of red bar (depending where you place your cursor e.g. first, middle, last line with error)
2-3 Not reproduced
