### ISSUE TITLE
User story: I want to read quality, detailed, and up-to-date docs for every wrapper

### ISSUE THREAD

**Issue by krisbitney** [polywrap/hub#179]
See [monorepo issue #702](https://github.com/polywrap/monorepo/issues/702), including Jordan's comment. The Hub should make it easy for developers to find schemas and documentation for wrappers. This could be implemented in any way that makes sense in the Hub's context.

**Comment by Burmenska** [comment]
As we discussed at the meeting we need to show README.md file content in the wrapper readme. If this file is absent then we need to show the following information:
```
# Get Started

## Install
yarn install ...

## Initialize
const api...

## Query
Query: get($a, $b)

const $a = '...';
const $b = '...';
api.invoke("get", $a, $b);
```

The query is first derived query from a schema

**Comment by krisbitney** [comment]
@Brioline @vrijzinnig Hi, could you guys give me a brief description of how this was implemented? What can users expect?

**Comment by krisbitney** [comment]
I re-opened the issue because the implementation does not seem to have met the described requirements

**Comment by Brioline** [comment]
Hi @krisbitney ! 
Currently hub uses metamanifest to show example query wrapper contains.
There is no schema parser implemented at the moment, as well as no docs or readme inside wrapper as far as I know.
If we want to show full raw schema, we have to figure out how it should look like

**Comment by ramilexe** [comment]
Hi @krisbitney 
Based on information we currently have about the wrapper we implemented logic as describe in Sandra's comment: https://github.com/polywrap/hub/issues/179#issuecomment-1073747274
