### ISSUE TITLE
Wrappers being duplicated in Playground

### ISSUE THREAD

**Issue by vrijzinnig** [polywrap/hub#181]
**Steps:**
Open Playground page
Click on a wrapper from drop-down list
Refresh the page

**AR:** Opened wrapper is duplicated (as many times as refresh button is clicked, they are also duplicated on Home page)
https://prnt.sc/6ZJGSkITSD8I
https://prnt.sc/R8hwq2Nzf6e8

**EX** Quantity of wrappers should not change

**Comment by vrijzinnig** [comment]
@Brioline Wrappers are duplicated when user clicks on Polywrap logo. https://i.imgur.com/QAxjpuL.gif

**Comment by Brioline** [comment]
Closed by: https://github.com/polywrap/hub/pull/207/commits/42cc6522ffbdd5011ff1bc5020e6741efc8ddc0e
