### ISSUE TITLE
Disconnect did authorization after wallet change

### ISSUE THREAD

**Issue by vrijzinnig** [polywrap/hub#184]

**Comment by Burmenska** [comment]
Need to check if the connected wallet is the same at was used for the authorization

**Comment by Brioline** [comment]
At the moment there is no way to change did without reloading page
DID is being created at the moment of Ceramic client initialization, so when we change address to address with diferent did, previous did is being used for initialization of ceramic

Example https://ceramicstudio.github.io/web-playground/

**Comment by Brioline** [comment]
Description in PR's comment section https://github.com/polywrap/hub/pull/247
