### ISSUE TITLE
UX Request: parsing uris for edgecases brings errors 

### ISSUE THREAD

**Issue by daoadvocate** [polywrap/hub#219]
when you use the playground uri input field, you are faced with several ways of inputing a uri, and we dont have a guide yet

![image](https://user-images.githubusercontent.com/102427768/160250644-d5be431c-a387-4a9e-a6a5-18a2d85ae8bb.png)

users can give 

/ipfs/Qm....
ipfs/Qm....
ens/polywrap.eth
/ens/polywrap.eth
polywrap.eth

these would be parsed by the frontend with some string handling and then set in a syntax so it can be approrpiately processed by the playground's polywrap client.

if this is too complex, let's add a tooltip and tell people what's the appropriate uri format, with a link to docs

**Comment by Brioline** [comment]
case for '/ens/...' sometimes didn't work, because there was an error related network, this wrapper isn't on.
Added error message display if an error occurs while loading api data or api content
