### ISSUE TITLE
Integrate Hub Discovery Backend with wrappers.io Persistence Node

### ISSUE THREAD

**Issue by eugenefine** [polywrap/hub#223]

**Comment by dOrgJelli** [comment]
@nerfZael could you describe how The Hub could ingress wrappers from the persistence node?

**Comment by nerfZael** [comment]
I added two issues that are blockers for this:
https://github.com/polywrap/nodes/issues/57
https://github.com/polywrap/wrappers-io/issues/2

The process would work like this:
Query ipfs.wrappers.io/pin/ls to get a list of pinned IPFS hashes and ENS nodes (if applicable)
Query tracking.wrappers.io/api/ens/resolve-many with the ENS nodes in the body of the request, to get the ENS domains for the nodes (if they can be found)
Combining those two requests you can get a list of IPFS hashes and ENS domain names for them (if they're registered on ENS)
