### ISSUE TITLE
Bug: ENS Domain Publishing - No Metadata

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/hub#226]
Currently wrappers without metadata cannot be published to The Hub. I think this itself is a problem, as well as the error messaging shown here is not very descriptive or constructive:
![image](https://user-images.githubusercontent.com/5522128/160725642-06dacf3a-158d-411e-8005-edae2f24021b.png)

**Comment by Brioline** [comment]
Blocked by: https://github.com/polywrap/hub/issues/147
