### ISSUE TITLE
Links for More tab

### ISSUE THREAD

**Issue by vrijzinnig** [polywrap/hub#232]
Remove Favorites 
https://prnt.sc/GbHQjMAE7T9L

Get links for the rest of menu items

**Comment by eugenefine** [comment]
Favorites - remove, move to Milestone 2
About - https://polywrap.io/
Docs - https://docs.polywrap.io/
Code - https://github.com/polywrap
Discord - https://discord.gg/bGsqQrNhqd
Analytics - remove, move to Milestone 2
