### ISSUE TITLE
Refactor: Fix Routing & Args

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/hub#65]
Refactor the app's routes & args to look like this:
1. Polywrapper Info Page: `https://hub.polywrap.io/info?uri="/ens/domain.eth"`
2. Polywrapper Query Page (prev "playground"): `https://hub.polywrap.io/query?uri="/ens/domain.eth"`

**Comment by ramilexe** [comment]
How should it work if we have only ipfs hash?

**Comment by dOrgJelli** [comment]
yes this is how polywrap URIs currently work. See here for more information: https://docs.polywrap.io/getting-started/understanding-uris
