### ISSUE TITLE
Refactor: Bottom-Up Backend URI Aggregation

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/hub#71]
Instead of having the backend only cache Polywrap URIs that are "published" through the "create" page, instead it should cache anything that it hasn't "seen" before.

This becomes a "push" model, where the different Polywrap Hub web clients will push new URIs to the backend every time they're viewed. This way, the backend is caching anything that users are viewing, and don't exist in the backend cache already.

**Comment by ramilexe** [comment]
@reenko 
Create a new API Endpoint to store Polywrap URI (ens/ipfs) in the database.
