### ISSUE TITLE
Refactor: Use IDX For Polywrap Favorites

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/hub#73]
Users can "favorite" polywrappers, which adds the URI to a list attached to their profile. We can utilize IDX/Ceramic for this, so it's attached to their DID, instead of storing them on the backend or localstorage.

Using IDX/Ceramic has the benefit of allowing these to be surfaced in other applications as well.

Currently, we can "hard-code" this, but in the future we should create a "Polywrap Hub" polywrapper, which could query into the IDX/Ceramic polywrapper.

**Comment by ramilexe** [comment]
- [x] create IDX definition for 
- [x] store favorites in IDX network 

* add `did` field to the user table in database
* add DID auth on frontend
* send user's eth address and DID after authorization to backend for caching
* on home page and search API requests pass user's DID
* add `favorites` table in database and write `user_id` and `api_id`
* when backend API returns wrapper list enrich it with favorites based on user-provided DID
