### ISSUE TITLE
UI Refactoring: Apply new design to Playground page

### ISSUE THREAD

**Issue by ramilexe** [polywrap/hub#87]
Apply this design to playground page: https://www.figma.com/proto/UKZdfPjOQ7wXxyOOayMJDG/Polywrap?page-id=0%3A1&node-id=276%3A5150&viewport=279%2C48%2C0.74&scaling=min-zoom&starting-point-node-id=272%3A2094

**Comment by Brioline** [comment]
https://github.com/polywrap/hub/pull/88
